<?php

namespace ContainerSi7pHbo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HR1sC65Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hR1sC65' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hR1sC65'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\PokemonController::image' => ['privates', '.service_locator.YorEgXw', 'get_ServiceLocator_YorEgXwService', true],
            'App\\Controller\\TeamController::addPokemon' => ['privates', '.service_locator.p02vx.n', 'get_ServiceLocator_P02vx_NService', true],
            'App\\Controller\\TeamController::get' => ['privates', '.service_locator.p02vx.n', 'get_ServiceLocator_P02vx_NService', true],
            'App\\Controller\\TeamController::removePokemon' => ['privates', '.service_locator.k2YJggB', 'get_ServiceLocator_K2YJggBService', true],
            'App\\Controller\\TeamController::store' => ['privates', '.service_locator.L9d3.bx', 'get_ServiceLocator_L9d3_BxService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\PokemonController:image' => ['privates', '.service_locator.YorEgXw', 'get_ServiceLocator_YorEgXwService', true],
            'App\\Controller\\TeamController:addPokemon' => ['privates', '.service_locator.p02vx.n', 'get_ServiceLocator_P02vx_NService', true],
            'App\\Controller\\TeamController:get' => ['privates', '.service_locator.p02vx.n', 'get_ServiceLocator_P02vx_NService', true],
            'App\\Controller\\TeamController:removePokemon' => ['privates', '.service_locator.k2YJggB', 'get_ServiceLocator_K2YJggBService', true],
            'App\\Controller\\TeamController:store' => ['privates', '.service_locator.L9d3.bx', 'get_ServiceLocator_L9d3_BxService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\PokemonController::image' => '?',
            'App\\Controller\\TeamController::addPokemon' => '?',
            'App\\Controller\\TeamController::get' => '?',
            'App\\Controller\\TeamController::removePokemon' => '?',
            'App\\Controller\\TeamController::store' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\PokemonController:image' => '?',
            'App\\Controller\\TeamController:addPokemon' => '?',
            'App\\Controller\\TeamController:get' => '?',
            'App\\Controller\\TeamController:removePokemon' => '?',
            'App\\Controller\\TeamController:store' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
