<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSi7pHbo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSi7pHbo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSi7pHbo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSi7pHbo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSi7pHbo\App_KernelDevDebugContainer([
    'container.build_hash' => 'Si7pHbo',
    'container.build_id' => '6cc63b45',
    'container.build_time' => 1663581775,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSi7pHbo');
