<?php

namespace ContainerSi7pHbo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P02vx_NService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p02vx.n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p02vx.n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'team' => ['privates', '.errored..service_locator.p02vx.n.App\\Entity\\Team', NULL, 'Cannot autowire service ".service_locator.p02vx.n": it references class "App\\Entity\\Team" but no such service exists.'],
        ], [
            'team' => 'App\\Entity\\Team',
        ]);
    }
}
