<?php

namespace ContainerSi7pHbo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportPokemonsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ImportPokemons' shared autowired service.
     *
     * @return \App\Command\ImportPokemons
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ImportPokemons.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PokeClient.php';

        $container->privates['App\\Command\\ImportPokemons'] = $instance = new \App\Command\ImportPokemons(new \App\Service\PokeClient(($container->privates['http_client'] ?? $container->load('getHttpClientService'))), ($container->services['doctrine'] ?? $container->getDoctrineService()));

        $instance->setName('app:import-pokemons');

        return $instance;
    }
}
