<?php

namespace ContainerXrn383a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YorEgXwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YorEgXw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YorEgXw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pokemon' => ['privates', '.errored..service_locator.YorEgXw.App\\Entity\\Pokemon', NULL, 'Cannot autowire service ".service_locator.YorEgXw": it references class "App\\Entity\\Pokemon" but no such service exists.'],
        ], [
            'pokemon' => 'App\\Entity\\Pokemon',
        ]);
    }
}
