<?php

namespace ContainerXrn383a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPokemonService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YorEgXw.App\Entity\Pokemon' shared service.
     *
     * @return \App\Entity\Pokemon
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.YorEgXw": it references class "App\\Entity\\Pokemon" but no such service exists.');
    }
}
