<?php

namespace ContainerXrn383a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TeamController' shared autowired service.
     *
     * @return \App\Controller\TeamController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/TeamController.php';

        $container->services['App\\Controller\\TeamController'] = $instance = new \App\Controller\TeamController(($container->services['doctrine'] ?? $container->getDoctrineService()));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\TeamController', $container));

        return $instance;
    }
}
